/**
 * Compiles every fund type version's CashScript contracts into artifacts.
 *
 *   src/fund-types/<type>/<version>/contracts/<name>.cash
 *     -> src/fund-types/<type>/<version>/artifacts/<name>.json  (shipped as-is)
 *     -> src/fund-types/<type>/<version>/artifacts/<name>.ts    (typed `as const`, used by the builders)
 *
 * The JSON artifact is the source of truth. When a contract compiles to the same
 * bytecode as its committed artifact, the committed JSON is kept untouched so
 * rebuilding does not churn `updatedAt`; the typed artifact is always regenerated
 * from the JSON.
 *
 * Usage:
 *   tsx scripts/build-contracts.ts            compile and write artifacts
 *   tsx scripts/build-contracts.ts --check    fail if any committed artifact is stale
 *   tsx scripts/build-contracts.ts --force    recompile and rewrite every artifact
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { compileFile, utils } from 'cashc';

type Artifact = ReturnType<typeof compileFile>;

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const fundTypesDir = path.join(root, 'src', 'fund-types');
const check = process.argv.includes('--check');
const force = process.argv.includes('--force');

const directories = (dir: string): string[] =>
    existsSync(dir)
        ? readdirSync(dir, { withFileTypes: true }).filter(d => d.isDirectory()).map(d => d.name)
        : [];

/**
 * The whole artifact except its timestamp. Debug info (logs, requires, source map)
 * and source must be included: a console.log or require message changes them
 * without changing the bytecode.
 */
const fingerprint = ({ updatedAt: _, ...artifact }: Artifact): string => JSON.stringify(artifact);

const relative = (file: string): string => path.relative(root, file).replaceAll('\\', '/');

/** 'TransactionManager' -> 'transactionManager' */
const camelCase = (contractName: string): string => contractName.charAt(0).toLowerCase() + contractName.slice(1);

const IndexHeader = [
    '// Compiled contract artifacts, typed `as const` and keyed by contract name.',
    '// Generated by `yarn build:contracts` along with the .json and .ts artifacts; do not edit.',
    '',
].join('\n');

const stale: string[] = [];
let compiled = 0;

for (const type of directories(fundTypesDir)) {
    for (const version of directories(path.join(fundTypesDir, type))) {
        const contractsDir = path.join(fundTypesDir, type, version, 'contracts');
        const artifactsDir = path.join(fundTypesDir, type, version, 'artifacts');
        if (!existsSync(contractsDir)) {
            continue;
        }

        const sources = readdirSync(contractsDir).filter(f => f.endsWith('.cash')).sort();
        const indexEntries: string[] = [];
        for (const source of sources) {
            const name = path.basename(source, '.cash');
            const jsonFile = path.join(artifactsDir, `${name}.json`);
            const tsFile = path.join(artifactsDir, `${name}.ts`);

            const fresh = compileFile(path.join(contractsDir, source));
            const committed: Artifact | undefined = existsSync(jsonFile)
                ? JSON.parse(readFileSync(jsonFile, 'utf8'))
                : undefined;

            const upToDate = !force && committed !== undefined && fingerprint(committed) === fingerprint(fresh);
            const artifact = upToDate ? committed : fresh;
            const typed = utils.formatArtifact(artifact, 'ts');
            const typedUpToDate = existsSync(tsFile) && readFileSync(tsFile, 'utf8') === typed;

            compiled += 1;
            indexEntries.push(`export { default as ${camelCase(artifact.contractName)} } from './${name}.js';`);

            if (check) {
                if (!upToDate) stale.push(relative(jsonFile));
                if (!typedUpToDate) stale.push(relative(tsFile));
                continue;
            }

            if (!upToDate) {
                writeFileSync(jsonFile, utils.formatArtifact(fresh, 'json'));
                console.log(`compiled ${relative(jsonFile)}`);
            }
            if (!typedUpToDate) {
                writeFileSync(tsFile, typed);
                console.log(`wrote    ${relative(tsFile)}`);
            }
        }

        if (!sources.length) {
            continue;
        }
        const indexFile = path.join(artifactsDir, 'index.ts');
        const index = `${IndexHeader}${indexEntries.join('\n')}\n`;
        const indexUpToDate = existsSync(indexFile) && readFileSync(indexFile, 'utf8') === index;
        if (check && !indexUpToDate) {
            stale.push(relative(indexFile));
        } else if (!check && !indexUpToDate) {
            writeFileSync(indexFile, index);
            console.log(`wrote    ${relative(indexFile)}`);
        }
    }
}

if (check) {
    if (stale.length) {
        console.error(`Stale contract artifacts (run \`yarn build:contracts\`):\n  ${stale.join('\n  ')}`);
        process.exit(1);
    }
    console.log(`All ${compiled} contract artifacts are up to date.`);
} else {
    console.log(`Checked ${compiled} contracts.`);
}
